import Hero from "@/components/Hero";
import Navbar from "@/components/Navbar";
import Slider from "@/components/Slider";
import Head from "next/head";
import Image from "next/image";
import sponge from "../../public/sponge.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>NFT - STAR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex items-center justify-center bg-black lg:hidden fixed h-[100vh] w-[100vw] z-50 ">
        <h2 className="text-lg md:text-xl text-white font-bold">
          Mobile / Tab Version is Still Under Development...
        </h2>
      </div>

      <div className="hidden lg:block w-[100vw] xl:h-[130vh] 2xl:h-screen relative">
        <div className="absolute w-full  h-full  background_image"></div>
        <Navbar />
        <Hero />
        <Slider />
        <div className="absolute bottom-0 flex items-center justify-center w-full">
          <p className="text-sm">Design by Coded by CodeStarGm</p>
        </div>

        <div className="absolute -bottom-0 right-0 ">
          <Image src={sponge} width={400} height={400}></Image>
        </div>
      </div>
    </>
  );
}
